'use client'

import {useRef} from 'react'
import {useTranslations} from 'next-intl'
import type {Project} from './project-data'
import {RepositoryTree} from './repository-tree'
import {useScrollReveal} from '@/app/hooks/use-scroll-reveal'
import {getProjectInsight} from '@/messages/project-insights'
import {ProjectLogo} from './project-logo'

export function ProjectDetailPage({project}:{project:Project}){
  const t=useTranslations('Projects')
  const detail=useTranslations('ProjectDetail')
  const insight=getProjectInsight(project.id)
  const treeStats=project.tree.reduce((total,node)=>{const walk=(item:typeof node):{folders:number;files:number}=>item.type==='file'?{folders:0,files:1}:(item.children??[]).reduce((sum,child)=>{const count=walk(child);return{folders:sum.folders+count.folders,files:sum.files+count.files}},{folders:1,files:0});const count=walk(node);return{folders:total.folders+count.folders,files:total.files+count.files}},{folders:0,files:0})
  const root=useRef<HTMLDivElement>(null)
  useScrollReveal(root,'.detail-reveal')
  const chip='rounded-full border border-[color-mix(in_srgb,var(--paper)_24%,transparent)] px-2.5 py-[7px] text-label opacity-78'
  return <article ref={root} className="editorial-page project-detail mx-auto w-[calc(100%_-_36px)] max-w-[1180px] pt-4 md:w-[min(1180px,91vw)] md:pt-[clamp(78px,9vh,108px)]">
    <a className="detail-back detail-reveal mx-auto mb-[35px] flex w-max text-label font-bold tracking-[.13em] text-inherit uppercase no-underline opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:mx-0 md:mb-[55px] md:inline-flex" href="/projetos">← {detail('back')}</a>
    <header className="detail-header detail-reveal grid grid-cols-1 [grid-template-areas:'eyebrow'_'logo'_'title'_'description'] justify-items-center gap-5 border-b border-[color-mix(in_srgb,var(--paper)_25%,transparent)] pb-[34px] text-center opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:grid-cols-[minmax(0,1fr)_minmax(220px,.32fr)] md:[grid-template-areas:'eyebrow_logo'_'title_logo'_'description_logo'] md:items-end md:justify-items-stretch md:gap-x-12 md:gap-y-5 md:pb-[55px] md:text-left"><p className="m-0 [grid-area:eyebrow] text-label font-[750] tracking-[.18em] uppercase opacity-50">{t(`groups.${project.group}`)}</p><ProjectLogo id={project.id} title={project.title} className="aspect-[5/4] w-[min(260px,76vw)] [grid-area:logo] rounded-[22px] md:w-full md:self-stretch"/><h1 className="m-0 max-w-full [grid-area:title] [overflow-wrap:anywhere] font-display text-[clamp(43px,14vw,58px)] leading-[.84] font-normal tracking-[-.055em] md:text-[clamp(58px,8vw,112px)] md:leading-[.78]">{project.title}</h1><span className="max-w-[48ch] [grid-area:description] text-body leading-[1.65] opacity-70 md:text-[13px] md:leading-[1.75]">{t(`items.${project.id}`)}</span></header>
    <section className="detail-specs detail-reveal mt-7 grid grid-cols-1 justify-items-center gap-8 border-b border-[color-mix(in_srgb,var(--paper)_18%,transparent)] py-[30px] text-center opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:mt-[46px] md:grid-cols-2 md:justify-items-stretch md:gap-[60px] md:py-[38px] md:text-left"><div><p className="mt-0 mb-5 text-caption font-[750] tracking-[.17em] uppercase opacity-50">{detail('services')}</p><ul className="m-0 flex list-none flex-wrap justify-center gap-2 p-0 md:justify-start">{project.services.map(service=><li className="bg-[color-mix(in_srgb,var(--paper)_9%,transparent)] px-3 py-[7px] text-label opacity-78" key={service}>{service}</li>)}</ul></div><div><p className="mt-0 mb-5 text-caption font-[750] tracking-[.17em] uppercase opacity-50">{detail('technologies')}</p><ul className="m-0 flex list-none flex-wrap justify-center gap-2 p-0 md:justify-start">{project.technologies.map(technology=><li className={chip} key={technology}>{technology}</li>)}</ul></div></section>
    <section className="system-section detail-reveal mt-12 border-b border-[color-mix(in_srgb,var(--paper)_24%,transparent)] pb-12 opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:mt-20 md:pb-20" aria-labelledby="system-title">
      <header className="grid grid-cols-1 items-end gap-6 text-center md:grid-cols-[minmax(0,.7fr)_minmax(320px,1fr)] md:gap-16 md:text-left"><div><p className="m-0 text-caption font-[750] tracking-[.18em] uppercase opacity-58">{detail('systemEyebrow')}</p><h2 className="my-3 font-display text-[clamp(40px,11vw,54px)] leading-[.86] font-normal md:text-[clamp(48px,6vw,78px)]" id="system-title">{detail('systemTitle')}</h2></div><p className="m-0 text-body leading-[1.75] opacity-78">{insight.overview}</p></header>
      <div className="mt-10 grid grid-cols-1 gap-px bg-[color-mix(in_srgb,var(--paper)_28%,transparent)] md:mt-14 md:grid-cols-3">{insight.architecture.map((item,index)=><article className="min-h-[180px] bg-[color-mix(in_srgb,var(--ink)_94%,transparent)] p-6 text-center md:min-h-[230px] md:p-7 md:text-left" key={item.name}><span className="editorial-number font-display text-base">{String(index+1).padStart(2,'0')}</span><h3 className="mt-8 mb-3 font-display text-[clamp(27px,3vw,37px)] leading-[.94] font-normal md:mt-12">{item.name}</h3><p className="m-0 text-body-sm leading-[1.7] opacity-72">{item.role}</p></article>)}</div>
    </section>
    <section className="engineering-section detail-reveal mt-12 grid grid-cols-1 gap-12 border-b border-[color-mix(in_srgb,var(--paper)_24%,transparent)] pb-12 opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:mt-20 md:grid-cols-[minmax(0,1fr)_minmax(260px,.42fr)] md:gap-20 md:pb-20">
      <div><p className="m-0 text-caption font-[750] tracking-[.18em] uppercase opacity-58">{detail('flow')}</p><ol className="mt-7 grid list-none gap-0 p-0">{insight.flow.map((step,index)=><li className="grid grid-cols-[34px_1fr] gap-4 border-t border-[color-mix(in_srgb,var(--paper)_22%,transparent)] py-5 first:border-t-0 first:pt-0" key={step}><span className="editorial-number font-display text-base">{String(index+1).padStart(2,'0')}</span><p className="m-0 font-display text-[clamp(22px,3vw,30px)] leading-[1.05]">{step}</p></li>)}</ol></div>
      <aside className="border-t border-[color-mix(in_srgb,var(--paper)_34%,transparent)] pt-6 md:border-t-0 md:border-l md:pt-0 md:pl-8"><p className="m-0 text-caption font-[750] tracking-[.18em] uppercase opacity-58">{detail('decisions')}</p><ul className="mt-6 grid list-none gap-4 p-0">{insight.highlights.map(item=><li className="relative pl-5 text-body-sm leading-[1.65] opacity-78 before:absolute before:top-[.62em] before:left-0 before:h-1.5 before:w-1.5 before:rounded-full before:bg-paper before:content-['']" key={item}>{item}</li>)}</ul></aside>
    </section>
    <section className="repository-section detail-reveal mt-11 grid grid-cols-1 justify-items-center gap-[34px] text-center opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:mt-[70px] md:grid-cols-[minmax(230px,.55fr)_minmax(0,1fr)] md:justify-items-stretch md:gap-[65px] md:text-left">
      <div><p className="m-0 text-caption font-[750] tracking-[.18em] uppercase opacity-48">{detail('eyebrow')}</p><h2 className="my-[17px] font-display text-[clamp(38px,12vw,52px)] leading-[.86] font-normal md:text-[clamp(39px,5vw,68px)]">{detail('title')}</h2><span className="mx-auto block max-w-[34ch] text-body leading-[1.7] opacity-68 md:mx-0">{detail(project.treeSource==='reconstructed'?'descriptionReconstructed':'description')}</span><code className="mx-auto mt-7 block [overflow-wrap:anywhere] text-small opacity-45 md:mx-0">{project.repository}</code>{project.url&&<a className="mt-[30px] inline-flex border-b border-current pb-1 text-label font-bold tracking-[.12em] text-inherit uppercase no-underline" href={project.url} target="_blank" rel="noreferrer">{detail('visit')} ↗</a>}</div>
      <div className="w-full text-left"><div className="flex min-h-10.5 flex-wrap items-center gap-1.5 rounded-t-[17px] border border-b-0 border-[color-mix(in_srgb,var(--paper)_24%,transparent)] bg-[color-mix(in_srgb,var(--ink)_82%,transparent)] px-[15px] py-2"><i className="h-[7px] w-[7px] rounded-full border border-[color-mix(in_srgb,var(--paper)_48%,transparent)]"/><i className="h-[7px] w-[7px] rounded-full border border-[color-mix(in_srgb,var(--paper)_48%,transparent)]"/><i className="h-[7px] w-[7px] rounded-full border border-[color-mix(in_srgb,var(--paper)_48%,transparent)]"/><span className="ml-auto font-mono text-label opacity-62">{treeStats.folders} pastas · {treeStats.files} arquivos</span></div><RepositoryTree nodes={project.tree}/></div>
    </section>
  </article>
}
