'use client'

import {useRef} from 'react'
import {useTranslations} from 'next-intl'
import Link from 'next/link'
import {projects} from './project-data'
import {useScrollReveal} from '@/app/hooks/use-scroll-reveal'

export function ProjectsPage(){
  const t=useTranslations('Projects')
  const root=useRef<HTMLDivElement>(null)
  useScrollReveal(root,'.project-reveal')
  const columns=(['personal','professional'] as const).map(group=>({group,items:projects.filter(project=>project.group===group).sort((a,b)=>Number(b.id==='asicarus')-Number(a.id==='asicarus'))}))
  const action='inline-flex items-center gap-[9px] rounded-full border border-[color-mix(in_srgb,var(--paper)_35%,transparent)] px-2.5 py-[9px] text-caption font-bold tracking-[.09em] text-inherit uppercase no-underline hover:bg-paper hover:text-ink md:gap-[13px] md:px-[11px] md:py-2'
  return <div ref={root} className="editorial-page mx-auto min-h-svh w-[calc(100%_-_36px)] pt-4 pb-6 md:w-[min(1180px,91vw)] md:pt-[clamp(78px,9vh,108px)] md:pb-[120px]">
    <header className="page-heading project-reveal grid grid-cols-1 justify-items-center gap-5 border-b border-[color-mix(in_srgb,var(--paper)_28%,transparent)] pb-[34px] text-center opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:grid-cols-[minmax(0,1fr)_minmax(260px,.42fr)] md:items-end md:justify-items-stretch md:gap-[60px] md:pb-[58px] md:text-left"><p className="col-start-1 m-0 text-label font-[750] tracking-[.2em] uppercase opacity-55 md:col-span-2">{t('eyebrow')}</p><h1 className="m-0 max-w-full [overflow-wrap:anywhere] font-display text-[clamp(45px,15vw,60px)] leading-[.84] font-normal tracking-[-.055em] md:text-[clamp(62px,10vw,148px)] md:leading-[.76]">{t('title')}</h1><span className="max-w-[36ch] text-body leading-[1.65] opacity-68 md:max-w-none md:text-[13px] md:leading-[1.8]">{t('description')}</span></header>
    <div className="project-columns mt-[38px] grid grid-cols-1 gap-[54px] md:mt-[55px] md:grid-cols-2 md:gap-[clamp(40px,7vw,100px)]">{columns.map(column=><section className="project-column" key={column.group}><details className="group/details w-full" open><summary className="project-reveal grid cursor-pointer list-none grid-cols-[auto_auto_24px] items-center justify-center gap-3.5 border-b border-[color-mix(in_srgb,var(--paper)_42%,transparent)] pb-[18px] text-center opacity-0 marker:hidden motion-reduce:opacity-100 motion-reduce:transform-none md:grid-cols-[1fr_auto_24px] md:justify-stretch md:text-left"><h2 className="m-0 font-display text-[clamp(32px,3.5vw,50px)] font-normal">{t(`groups.${column.group}`)}</h2><span className="font-display text-lg opacity-45">{String(column.items.length).padStart(2,'0')}</span><i className="relative h-5 w-5 rounded-full border border-[color-mix(in_srgb,var(--paper)_34%,transparent)] before:absolute before:top-1/2 before:left-1/2 before:h-px before:w-2 before:-translate-x-1/2 before:-translate-y-1/2 before:bg-current before:content-[''] after:absolute after:top-1/2 after:left-1/2 after:h-px after:w-2 after:-translate-x-1/2 after:-translate-y-1/2 after:rotate-90 after:bg-current after:content-[''] after:transition-transform after:duration-250 group-open/details:after:rotate-0" aria-hidden="true"/></summary><div>{column.items.map((project,index)=><article className={`project-entry project-reveal grid grid-cols-1 justify-items-center gap-2.5 border-b border-[color-mix(in_srgb,var(--paper)_20%,transparent)] py-[30px] text-center opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:grid-cols-[34px_1fr] md:justify-items-stretch md:gap-[15px] md:py-[34px] md:text-left ${index===column.items.length-1?'max-md:border-b-0':''}`} key={project.id}>
      <span className="pt-0 font-display text-[15px] opacity-40 md:pt-[5px]">{String(index+1).padStart(2,'0')}</span>
      <div><h3 className="m-0 [overflow-wrap:anywhere] font-display text-[clamp(31px,10vw,39px)] leading-[.9] font-normal md:text-[clamp(30px,3vw,45px)]">{project.title}</h3><p className="mt-[15px] mb-0 text-body-sm leading-[1.7] opacity-68">{t(`items.${project.id}`)}</p><ul className="mt-[17px] mb-0 flex list-none flex-wrap justify-center gap-1.5 p-0 md:justify-start">{project.tags.map(tag=><li className="rounded-full border border-[color-mix(in_srgb,var(--paper)_22%,transparent)] px-[9px] py-[5px] text-caption tracking-[.07em] uppercase opacity-72" key={tag}>{tag}</li>)}</ul><div className="mt-5 flex flex-wrap justify-center gap-[7px] md:justify-start md:gap-2.5"><Link className={action} href={`/projetos/${project.id}`}>{t('details')} <span className="font-display text-[15px] leading-none">→</span></Link>{project.url&&<a className={action} href={project.url} target="_blank" rel="noreferrer">{t('external')} <span className="font-display text-[15px] leading-none">↗</span></a>}</div></div>
    </article>)}</div></details></section>)}</div>
  </div>
}
