'use client'

import {useRef} from 'react'
import {useTranslations} from 'next-intl'
import type {Project} from './project-data'
import {RepositoryTree} from './repository-tree'
import {useScrollReveal} from '@/app/hooks/use-scroll-reveal'

export function ProjectDetailPage({project}:{project:Project}){
  const t=useTranslations('Projects')
  const detail=useTranslations('ProjectDetail')
  const root=useRef<HTMLDivElement>(null)
  useScrollReveal(root,'.detail-reveal')
  const chip='rounded-full border border-[color-mix(in_srgb,var(--paper)_24%,transparent)] px-2.5 py-[7px] text-label opacity-78'
  return <article ref={root} className="editorial-page project-detail mx-auto min-h-svh w-[calc(100%_-_36px)] max-w-[1180px] pt-4 md:w-[min(1180px,91vw)] md:pt-[clamp(78px,9vh,108px)]">
    <a className="detail-back detail-reveal mx-auto mb-[35px] flex w-max text-label font-bold tracking-[.13em] text-inherit uppercase no-underline opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:mx-0 md:mb-[55px] md:inline-flex" href="/projetos">← {detail('back')}</a>
    <header className="detail-header detail-reveal grid grid-cols-1 justify-items-center gap-5 border-b border-[color-mix(in_srgb,var(--paper)_25%,transparent)] pb-[34px] text-center opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:grid-cols-[minmax(0,1fr)_minmax(260px,.42fr)] md:items-end md:justify-items-stretch md:gap-[38px] md:pb-[55px] md:text-left"><p className="col-start-1 m-0 text-label font-[750] tracking-[.18em] uppercase opacity-50 md:col-span-2">{t(`groups.${project.group}`)}</p><h1 className="m-0 max-w-full [overflow-wrap:anywhere] font-display text-[clamp(43px,14vw,58px)] leading-[.84] font-normal tracking-[-.055em] md:text-[clamp(64px,10vw,145px)] md:leading-[.76]">{project.title}</h1><span className="text-body leading-[1.65] opacity-70 md:text-[13px] md:leading-[1.75]">{t(`items.${project.id}`)}</span></header>
    <div className="detail-tags detail-reveal flex flex-wrap justify-center gap-2 py-5 opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:justify-start md:py-[26px]">{project.tags.map(tag=><span className="rounded-full border border-[color-mix(in_srgb,var(--paper)_22%,transparent)] px-2.5 py-1.5 text-caption tracking-[.08em] uppercase" key={tag}>{tag}</span>)}</div>
    <section className="detail-specs detail-reveal mt-7 grid grid-cols-1 justify-items-center gap-8 border-y border-[color-mix(in_srgb,var(--paper)_18%,transparent)] py-[30px] text-center opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:mt-[46px] md:grid-cols-2 md:justify-items-stretch md:gap-[60px] md:py-[38px] md:text-left"><div><p className="mt-0 mb-5 text-caption font-[750] tracking-[.17em] uppercase opacity-50">{detail('services')}</p><ul className="m-0 flex list-none flex-wrap justify-center gap-2 p-0 md:justify-start">{project.services.map(service=><li className="bg-[color-mix(in_srgb,var(--paper)_9%,transparent)] px-3 py-[7px] text-label opacity-78" key={service}>{service}</li>)}</ul></div><div><p className="mt-0 mb-5 text-caption font-[750] tracking-[.17em] uppercase opacity-50">{detail('technologies')}</p><ul className="m-0 flex list-none flex-wrap justify-center gap-2 p-0 md:justify-start">{project.technologies.map(technology=><li className={chip} key={technology}>{technology}</li>)}</ul></div></section>
    <section className="repository-section detail-reveal mt-11 grid grid-cols-1 justify-items-center gap-[34px] text-center opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:mt-[70px] md:grid-cols-[minmax(230px,.55fr)_minmax(0,1fr)] md:justify-items-stretch md:gap-[65px] md:text-left">
      <div><p className="m-0 text-caption font-[750] tracking-[.18em] uppercase opacity-48">{detail('eyebrow')}</p><h2 className="my-[17px] font-display text-[clamp(38px,12vw,52px)] leading-[.86] font-normal md:text-[clamp(39px,5vw,68px)]">{detail('title')}</h2><span className="mx-auto block max-w-[34ch] text-body leading-[1.7] opacity-68 md:mx-0">{detail(project.treeSource==='reconstructed'?'descriptionReconstructed':'description')}</span><code className="mx-auto mt-7 block [overflow-wrap:anywhere] text-small opacity-45 md:mx-0">{project.repository}</code>{project.url&&<a className="mt-[30px] inline-flex border-b border-current pb-1 text-label font-bold tracking-[.12em] text-inherit uppercase no-underline" href={project.url} target="_blank" rel="noreferrer">{detail('visit')} ↗</a>}</div>
      <div className="w-full text-left"><div className="flex h-10.5 items-center gap-1.5 rounded-t-[17px] border border-b-0 border-[color-mix(in_srgb,var(--paper)_24%,transparent)] bg-[color-mix(in_srgb,var(--ink)_82%,transparent)] px-[15px]"><i className="h-[7px] w-[7px] rounded-full border border-[color-mix(in_srgb,var(--paper)_48%,transparent)]"/><i className="h-[7px] w-[7px] rounded-full border border-[color-mix(in_srgb,var(--paper)_48%,transparent)]"/><i className="h-[7px] w-[7px] rounded-full border border-[color-mix(in_srgb,var(--paper)_48%,transparent)]"/><span className="ml-auto font-mono text-label opacity-42">{project.title.toLowerCase().replaceAll(' ','-')}</span></div><RepositoryTree nodes={project.tree}/></div>
    </section>
  </article>
}
