export type TreeNode={name:string;type:'folder'|'file';children?:TreeNode[]}
export type Project={id:string;title:string;group:'personal'|'professional';url?:string;tags:readonly string[];technologies:readonly string[];services:readonly string[];repository:string;treeSource?:'reconstructed';tree:TreeNode[]}

const folder=(name:string,children:TreeNode[]=[]):TreeNode=>({name,type:'folder',children})
const file=(name:string):TreeNode=>({name,type:'file'})

export const projects:Project[]=[
  {id:'fertec',title:'Fertec',group:'personal',url:'https://github.com/ferforastieri/fertech',repository:'pessoal/fertec',tags:['Next.js','TypeScript','Anime.js'],technologies:['Next.js 16','React 19','TypeScript','CSS modular','Anime.js 4','next-intl','Manrope','Instrument Serif'],services:['Portfolio web','Sistema de animação','Internacionalização','Temas persistentes'],tree:[folder('app',[folder('(portfolio)',[folder('projetos',[folder('[slug]')]),folder('sobre'),file('page.tsx')]),folder('components',[folder('ui',[file('ui.css')]),folder('portfolio',[file('portfolio.css')]),folder('projects',[file('projects.css')]),folder('about',[file('about.css')])]),file('globals.css')]),folder('i18n',[file('request.ts')]),folder('messages',[file('pt-BR.json'),file('en.json'),file('es.json')]),folder('public',[folder('assets')]),file('next.config.ts')]},
  {id:'atacte',title:'Atacte',group:'personal',url:'https://github.com/ferforastieri/atacte',repository:'pessoal/atacte',tags:['Vue 3','Expo','Express'],technologies:['Vue 3','Pinia','Vue Router','React Native','Expo','Electron','Express','Prisma','PostgreSQL','JWT','TOTP','AES-256','Tailwind CSS'],services:['API segura','Cliente web','Aplicativo mobile','Aplicativo desktop','Proxy Nginx'],tree:[folder('backend',[folder('src',[folder('controllers',[folder('auth'),folder('passwords'),folder('secureNotes'),folder('totp')]),folder('repositories'),folder('services'),folder('middleware'),folder('infrastructure')])]),folder('desktop'),folder('mobile',[folder('assets'),folder('src')]),folder('web',[folder('public'),folder('src',[folder('components'),folder('stores'),folder('views'),folder('api')])]),folder('nginx'),folder('scripts')]},
  {id:'valk',title:'Valk UI',group:'personal',url:'https://valkui.vercel.app',repository:'github/ferforastieri/valk-ui',treeSource:'reconstructed',tags:['React','TypeScript','CLI'],technologies:['React','TypeScript','Tailwind CSS','Node.js CLI'],services:['Biblioteca de componentes','CLI de instalação','Documentação','Sistema de temas'],tree:[folder('src',[folder('components'),folder('cli'),folder('lib'),folder('styles')]),folder('docs'),folder('templates'),file('package.json')]},
  {id:'asicarus',title:'ASICARUS',group:'personal',repository:'pessoal/asicarus',tags:['.NET 10','Game Server','Next.js'],technologies:['.NET 10 LTS','ASP.NET Core','Entity Framework Core','PostgreSQL 18','Redis','Npgsql','Next.js 16','React 19','Docker Compose','Python','Git LFS','AES-128'],services:['API de identidade','Portal do jogador','Launcher e cliente PC','Login Gateway','Coordinator','Lobby e World Server','Migração do legado','Infraestrutura Linux'],tree:[folder('api',[folder('src',[folder('Asicarus.Api'),folder('Asicarus.Application'),folder('Asicarus.Domain'),folder('Asicarus.Infrastructure',[folder('Persistence',[folder('Migrations')])])]),folder('tests',[folder('Asicarus.Api.Tests')]),folder('database'),folder('docs')]),folder('game-server',[folder('services',[folder('coordinator',[folder('Asicarus.Coordinator.Core')]),folder('login'),folder('lobby'),folder('world')]),folder('libraries',[folder('contracts',[folder('Asicarus.Game.Contracts')]),folder('protocol-legacy',[folder('Asicarus.LegacyProtocol')]),folder('networking'),folder('game-data')]),folder('tests',[folder('Asicarus.Coordinator.Tests'),folder('Asicarus.LegacyProtocol.Tests')]),folder('tools'),folder('docs')]),folder('game-clients',[folder('client-pc'),folder('client-mobile'),folder('launcher')]),folder('portal',[folder('web',[folder('app')]),folder('mobile')]),folder('infra',[folder('proxmox'),folder('tunnel'),folder('vm'),file('compose.yml')]),folder('legacy',[folder('game'),folder('api'),folder('database'),folder('tools')])]},
  {id:'vendedor',title:'Vendedor Gold',group:'professional',url:'https://vendedorgold.com.br',repository:'smart/vendedor-gold',tags:['React Native','React','NestJS'],technologies:['React','React Native','Expo','TypeScript','NestJS','TypeORM','PostgreSQL','MongoDB','Firebase','Socket.IO','React Query','Zustand','Recharts'],services:['API NestJS','Firebase Functions','Painel web','Aplicativo mobile','Notificações e tempo real'],tree:[folder('backend',[folder('src',[folder('auth'),folder('business-unit'),folder('client'),folder('goldia'),folder('notification'),folder('order'),folder('popup')])]),folder('backend-firebase',[folder('functions')]),folder('mobile',[folder('src')]),folder('web',[folder('public'),folder('src',[folder('api'),folder('components'),folder('assets')])])]},
  {id:'smart',title:'Smart',group:'professional',repository:'smart/smart',tags:['Express','React','MySQL'],technologies:['Node.js','Express 4','React 16','Sequelize','MySQL','MongoDB','Mongoose','Bee-Queue','JWT','Reactstrap','CoreUI','Material UI','Chart.js','Draft.js','Node Cron','Nodemailer','SFTP'],services:['API de fidelidade','Painel administrativo','Campanhas de e-mail e SMS','Filas e rotinas agendadas','Pontuação e resgates','Cartões-presente','Relatórios e dashboards'],tree:[folder('api',[folder('scripts',[file('01_update_idLojaOrigem.js')]),folder('src',[folder('app',[folder('controllers',[file('AuthenticationController.js'),file('CampaignController.js'),file('CustomerControlller.js'),file('DashboardController.js'),file('GiftController.js'),file('RescueController.js'),file('SaleController.js')]),folder('middlewares'),folder('models',[file('Campanha.js'),file('Cliente.js'),file('Fidelidades.js'),file('Pontuacao.js'),file('Premio.js'),file('Resgate.js'),file('Venda.js')]),folder('schemas')]),folder('config',[file('EmailMarketingAPI.js'),file('Mongoose.js'),file('Sequelize.js'),file('SMSMarketingAPI.js')]),folder('database'),folder('jobs',[file('ExpireScore.job.js'),file('NewVendasRadical.job.js'),file('NewVendasSodimac.job.js')]),folder('lib'),folder('routes'),folder('services',[file('NovaVenda.js'),file('NovoEmailMarketing.js'),file('NovoSMSMarketing.js'),file('PontuarCliente.js')]),folder('utils')]),file('package.json')]),folder('web',[folder('public'),folder('src',[folder('components',[folder('Campanhas'),folder('Dashboard'),folder('GridClientes'),folder('GridProdutos'),folder('GridResgates'),folder('Widgets')]),folder('containers'),folder('context'),folder('routes'),folder('scss'),folder('services'),folder('views',[folder('Pages'),folder('Theme')])]),file('package.json')]),file('bitbucket-pipelines.yml'),file('pm2.json')]},
  {id:'parceiro',title:'Parceiro Gold',group:'professional',url:'https://parceirogold.com.br',repository:'smart/wpp-parceirogold',tags:['NestJS','Prisma','WhatsApp'],technologies:['NestJS','TypeScript','Prisma','Axios','Canvas','Jimp','RxJS'],services:['Automação WhatsApp','Geração de mídia','Persistência Prisma','Rotinas operacionais'],tree:[folder('src',[folder('config'),folder('helpers'),folder('scripts')]),folder('prisma'),folder('test'),folder('img',[folder('generated')]),folder('fonts')]},
  {id:'pintor',title:'Clube Pro Pintor',group:'professional',url:'https://clubepropintor.com.br',repository:'smart/sw-app',tags:['Ionic','Angular','Capacitor'],technologies:['Ionic','Angular','TypeScript','Capacitor','RxJS','Firebase Analytics','Firebase Cloud Messaging','Swiper'],services:['Aplicativo Ionic','Build Android','Build iOS','Push notifications','Analytics'],tree:[folder('src',[folder('app'),folder('assets'),folder('environments'),folder('theme')]),folder('android',[folder('app'),folder('gradle')]),folder('ios',[folder('App')]),folder('resources'),folder('e2e')]},
  {id:'dashboard',title:'Dashlab',group:'personal',url:'https://github.com/ferforastieri/dashlab',repository:'pessoal/dashlab',tags:['NestJS','React','Prisma'],technologies:['NestJS','React','TypeScript','Prisma','React Query','Vite','Tailwind CSS','Argon2','JWT','Sharp'],services:['API NestJS','Editor de dashboards','Autenticação','Processamento de imagens'],tree:[folder('backend',[folder('prisma'),folder('src',[folder('infrastructure',[folder('database')]),folder('modules',[folder('auth'),folder('dashboard')])])]),folder('web',[folder('public'),folder('scripts'),folder('src',[folder('api'),folder('components'),folder('pages')])]),folder('nginx'),folder('.gitea',[folder('workflows')])]},
  {id:'gabriel',title:'GabrielPro',group:'professional',url:'https://gabrielpro.com.br',repository:'smart/gabrielpro',tags:['Next.js','Express','Prisma'],technologies:['Next.js','React','TypeScript','Express','Prisma','Styled Components','Bootstrap','JWT','Winston','Node Schedule'],services:['API Express','Aplicação Next.js','Jobs agendados','Relatórios e dashboards'],tree:[folder('api',[folder('prisma'),folder('src',[folder('controllers'),folder('entities'),folder('infra'),folder('jobs'),folder('services'),folder('usecases')])]),folder('app',[folder('public'),folder('src',[folder('components'),folder('pages'),folder('services'),folder('views')])]),folder('nginx')]},
  {id:'recomenda',title:'SW Recomenda',group:'professional',repository:'smart/sw-recomenda',tags:['Ionic','React','NestJS'],technologies:['Ionic','Angular','React','Material UI','NestJS','Prisma','AWS S3','Firebase','SendGrid','Redux','Capacitor'],services:['Aplicativo Ionic','API NestJS','Portal React','Aplicação de push','Storage S3'],tree:[folder('app',[folder('android'),folder('ios'),folder('src')]),folder('backend',[folder('prisma'),folder('src',[folder('auth'),folder('localizacao'),folder('mail'),folder('notificacoesPush'),folder('pintores'),folder('servicosCategorias')])]),folder('frontend',[folder('public'),folder('src',[folder('components'),folder('pages'),folder('services')])]),folder('push',[folder('src')])]},
  {id:'leoplus',title:'LeoPlus',group:'professional',url:'https://leoplus.com.br',repository:'private/leoplus',treeSource:'reconstructed',tags:['React','TypeScript','APIs'],technologies:['React','TypeScript','Material UI','Zustand','React Query','REST APIs'],services:['Portal de fidelidade','Campanhas','Resgates','Integrações com parceiros'],tree:[folder('frontend',[folder('src',[folder('components'),folder('features'),folder('services')])]),folder('api',[folder('src',[folder('modules'),folder('integrations')])]),folder('infrastructure')]},
]

export function getProject(id:string){return projects.find(project=>project.id===id)}
