'use client'

import {useRef,useState} from 'react'
import {useTranslations} from 'next-intl'
import {useScrollReveal} from '@/app/hooks/use-scroll-reveal'
import {AuroraLab,type AuroraMotion,type AuroraScene,type AuroraSettings} from './aurora-lab'

const scenes:AuroraScene[]=['field','prism','signal','grid','tunnel','terrain','aim']
const motions:AuroraMotion[]=['orbit','wave','chaos']
const colors=['#ff5b3d','#eee6d9','#8da9ff','#b89cff','#7fcda6']

export function WebGLPage(){
  const t=useTranslations('WebGL')
  const root=useRef<HTMLDivElement>(null)
  const [settings,setSettings]=useState<AuroraSettings>({scene:'field',motion:'orbit',color:colors[0],density:110,speed:1,brush:3,paused:false,drawing:true})
  const [clearToken,setClearToken]=useState(0)
  useScrollReveal(root,'.webgl-reveal')
  const update=(next:Partial<AuroraSettings>)=>setSettings(current=>({...current,...next}))
  const selectScene=(scene:AuroraScene,event:React.MouseEvent<HTMLButtonElement>)=>{setClearToken(value=>value+1);update({scene});event.currentTarget.animate([{transform:'scale(.92)'},{transform:'scale(1)'}],{duration:430,easing:'cubic-bezier(.16,1,.3,1)'})}
  const randomize=()=>{setClearToken(value=>value+1);update({scene:scenes[Math.floor(Math.random()*scenes.length)],motion:motions[Math.floor(Math.random()*motions.length)],color:colors[Math.floor(Math.random()*colors.length)],density:55+Math.round(Math.random()*115),speed:Number((.45+Math.random()*1.7).toFixed(1))})}
  const controlButton='min-h-[34px] border border-[rgba(231,223,209,.2)] bg-transparent px-2 text-caption font-bold tracking-[.055em] text-inherit uppercase hover:border-[#eee6d9] hover:bg-[#eee6d9] hover:text-[#12110f] focus-visible:border-[#eee6d9] focus-visible:bg-[#eee6d9] focus-visible:text-[#12110f] focus-visible:outline-none'
  const activeControl='border-[#eee6d9] bg-[#eee6d9] text-[#12110f]'
  return <div ref={root} className="editorial-page webgl-page mx-auto min-h-svh w-[calc(100%_-_36px)] max-w-[1180px] pt-4 pb-6 md:w-[min(1180px,91vw)] md:pt-[clamp(78px,9vh,108px)] md:pb-[120px]">
    <header className="webgl-heading webgl-reveal grid grid-cols-1 justify-items-center gap-[18px] border-b border-[color-mix(in_srgb,var(--paper)_28%,transparent)] pb-8 text-center opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none md:grid-cols-[minmax(0,1fr)_minmax(260px,.42fr)] md:items-end md:justify-items-stretch md:gap-14 md:pb-[50px] md:text-left"><p className="col-start-1 m-0 text-label font-[750] tracking-[.2em] uppercase opacity-58 md:col-span-2">{t('eyebrow')}</p><h1 className="m-0 max-w-[9ch] font-display text-[clamp(45px,13vw,62px)] leading-[.83] font-normal tracking-[-.055em] md:text-[clamp(60px,9vw,126px)] md:leading-[.78]">{t('title')}</h1><span className="max-w-[36ch] text-body-sm leading-[1.75] opacity-72 md:max-w-none md:text-body">{t('description')}</span></header>
    <nav className="experiment-switcher webgl-reveal mt-[26px] flex snap-x overflow-x-auto border border-[color-mix(in_srgb,var(--paper)_24%,transparent)] opacity-0 motion-reduce:opacity-100 motion-reduce:transform-none" aria-label={t('experimentsLabel')}>{scenes.map((scene,index)=><button key={scene} type="button" aria-pressed={settings.scene===scene} className={`grid min-w-[118px] flex-[1_0_118px] snap-start gap-[13px] border-0 border-r border-[color-mix(in_srgb,var(--paper)_18%,transparent)] bg-transparent px-3 py-[15px] text-left text-inherit hover:bg-paper hover:text-ink focus-visible:bg-paper focus-visible:text-ink focus-visible:outline-none ${index===scenes.length-1?'border-r-0':''} ${settings.scene===scene?'shadow-[inset_0_-3px_0_#ff5b3d]':''}`} style={settings.scene===scene?{background:'#eee6d9',color:'#12110f'}:undefined} onClick={event=>selectScene(scene,event)}><span className="text-micro tracking-[.12em] opacity-55">{String(index+1).padStart(2,'0')}</span><strong className="overflow-hidden text-ellipsis whitespace-nowrap text-caption tracking-[.07em] uppercase">{t(`scenes.${scene}.title`)}</strong></button>)}</nav>
    <section className="webgl-console webgl-reveal mt-2 grid grid-cols-1 overflow-hidden rounded-b-[17px] border border-[color-mix(in_srgb,var(--paper)_26%,transparent)] bg-[#090907] opacity-0 shadow-[0_30px_80px_rgba(0,0,0,.25)] motion-reduce:opacity-100 motion-reduce:transform-none [[data-theme=light]_&]:shadow-[0_28px_70px_rgba(56,48,38,.15)] md:mt-2.5 min-[901px]:grid-cols-[minmax(0,1fr)_260px] min-[901px]:rounded-b-[22px]">
      <div className="relative min-h-[470px] overflow-hidden bg-[#090907] md:min-h-[610px]"><AuroraLab settings={settings} clearToken={clearToken} label={t('canvasLabel')}/><div className="pointer-events-none absolute top-[22px] right-[22px] left-[22px] max-w-[330px] text-center text-[#eee6d9] md:top-7 md:right-auto md:left-[30px] md:text-left"><code className="text-micro leading-[1.2] font-bold tracking-[.17em] uppercase opacity-55">{t(`scenes.${settings.scene}.eyebrow`)}</code><h2 className="mt-[9px] mb-[5px] font-display text-[clamp(31px,4vw,52px)] leading-[.9] font-normal tracking-[-.035em]">{t(`scenes.${settings.scene}.title`)}</h2><p className="mx-auto m-0 max-w-[38ch] text-label leading-[1.6] opacity-58 md:mx-0">{t(`scenes.${settings.scene}.description`)}</p></div><p className="absolute right-3.5 bottom-[15px] left-3.5 m-0 rounded-full border border-[rgba(231,223,209,.2)] bg-[rgba(15,15,13,.62)] px-2.5 py-[7px] text-center text-caption tracking-[.08em] text-[#e7dfd1] backdrop-blur-xl md:right-[22px] md:bottom-[19px] md:left-auto">{t(settings.drawing?'hint':'hintExplore')}</p><span className="absolute bottom-[25px] left-[30px] hidden text-micro leading-[1.2] font-bold tracking-[.17em] text-[#e7dfd1] uppercase opacity-55 md:block">{t('status')}</span></div>
      <aside className="grid grid-cols-1 gap-[21px] border-t border-[rgba(231,223,209,.17)] bg-[#12110f] p-5 text-[#eee6d9] md:grid-cols-2 md:gap-6 md:p-6 min-[901px]:flex min-[901px]:flex-col min-[901px]:border-t-0 min-[901px]:border-l" aria-label={t('controls')}>
        <header className="col-span-1 flex items-center justify-between border-b border-[rgba(231,223,209,.16)] pb-[18px] text-label font-[750] tracking-[.14em] uppercase md:col-span-2 min-[901px]:col-span-1"><span>{t('controls')}</span><i className={`h-[7px] w-[7px] rounded-full ${settings.paused?'bg-current opacity-25':'bg-[#9fc5a8] shadow-[0_0_12px_rgba(159,197,168,.7)]'}`}/></header>
        <fieldset className="m-0 border-0 p-0"><legend className="mb-2.5 text-caption font-bold tracking-[.13em] uppercase opacity-55">{t('motion')}</legend><div className="grid grid-cols-3 gap-1">{motions.map(motion=><button key={motion} className={`${controlButton} ${settings.motion===motion?activeControl:''}`} type="button" onClick={()=>update({motion})}>{t(`motions.${motion}`)}</button>)}</div></fieldset>
        <fieldset className="m-0 border-0 p-0"><legend className="mb-2.5 text-caption font-bold tracking-[.13em] uppercase opacity-55">{t('color')}</legend><div className="grid grid-cols-5 gap-1">{colors.map(color=><button key={color} type="button" className={`relative min-h-[27px] border-transparent p-0 ${settings.color===color?'shadow-[inset_0_0_0_2px_#12110f,0_0_0_1px_#eee6d9]':''}`} style={{background:color}} onClick={()=>update({color})} aria-label={`${t('color')} ${color}`}/>)}</div></fieldset>
        {([['elements',settings.density,30,180,1],['speed',settings.speed,0.2,2.5,0.1],['brush',settings.brush,1,8,1]] as const).map(([key,value,min,max,step])=><label className="grid grid-cols-[1fr_auto] items-center" key={key}><span className="mb-2.5 text-caption font-bold tracking-[.13em] uppercase opacity-55">{t(key)}</span><output className="font-display text-lg opacity-72">{key==='speed'?Number(value).toFixed(1):value}</output><input className="col-span-2 w-full accent-[#ff5b3d]" type="range" min={min} max={max} step={step} value={value} onChange={event=>update({[key==='elements'?'density':key]:Number(event.target.value)})}/></label>)}
        <button type="button" className={`${controlButton} w-full self-end ${settings.drawing?activeControl:''}`} onClick={()=>update({drawing:!settings.drawing})}>{t(settings.drawing?'drawingEnabled':'enableDrawing')}</button>
        <div className="col-span-1 mt-auto grid grid-cols-3 gap-1 md:col-span-2 min-[901px]:col-span-1"><button className={`${controlButton} px-0.75 text-micro`} type="button" onClick={()=>update({paused:!settings.paused})}>{t(settings.paused?'resume':'pause')}</button><button className={`${controlButton} px-0.75 text-micro`} type="button" onClick={randomize}>{t('randomize')}</button><button className={`${controlButton} px-0.75 text-micro`} type="button" onClick={()=>setClearToken(value=>value+1)}>{t('clear')}</button></div>
      </aside>
    </section>
  </div>
}
