'use client'

import { useEffect, useRef, useState } from 'react'
import { usePathname } from 'next/navigation'
import Lenis from 'lenis'
import { animate, stagger } from 'animejs'

export function Experience({children}:{children:React.ReactNode}){
  const pathname=usePathname();const cursor=useRef<HTMLDivElement>(null);const cursorLabel=useRef<HTMLSpanElement>(null);const[loading,setLoading]=useState(true);const[progress,setProgress]=useState(0)
  useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setProgress(100);setLoading(false);return}let value=0;const timer=window.setInterval(()=>{value=Math.min(100,value+Math.ceil((100-value)*.18));setProgress(value);if(value===100){clearInterval(timer);setTimeout(()=>setLoading(false),220)}},40);return()=>clearInterval(timer)},[])
  useEffect(()=>{const lenis=new Lenis({duration:1.15,smoothWheel:true,wheelMultiplier:.85});let frame=0;const raf=(time:number)=>{lenis.raf(time);frame=requestAnimationFrame(raf)};frame=requestAnimationFrame(raf);return()=>{cancelAnimationFrame(frame);lenis.destroy()}},[])
  useEffect(()=>{if(loading)return;animate('.header',{y:['-100%',0],duration:900,ease:'outExpo'});const targets=document.querySelectorAll<HTMLElement>('.manifesto h2,.section-head h2,.listing h1,.resume h1,.case header h1,.stack-row,.highlight,.article-grid>a');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const element=entry.target as HTMLElement;animate(element,{opacity:[0,1],y:[38,0],delay:stagger(40),duration:850,ease:'outExpo'});observer.unobserve(element)}),{threshold:.12});targets.forEach(target=>observer.observe(target));return()=>observer.disconnect()},[loading,pathname])
  useEffect(()=>{const node=cursor.current,label=cursorLabel.current;if(!node||!label)return;const move=(event:MouseEvent)=>animate(node,{x:event.clientX,y:event.clientY,duration:380,ease:'out(3)'});const enter=(event:Event)=>{const target=event.currentTarget as HTMLElement;node.classList.add('is-active');label.textContent=target.dataset.cursor||'OPEN'};const leave=()=>node.classList.remove('is-active');window.addEventListener('mousemove',move);const targets=document.querySelectorAll<HTMLElement>('a,.rail-project,.article-grid>a');targets.forEach(target=>{target.addEventListener('mouseenter',enter);target.addEventListener('mouseleave',leave)});return()=>{window.removeEventListener('mousemove',move);targets.forEach(target=>{target.removeEventListener('mouseenter',enter);target.removeEventListener('mouseleave',leave)})}},[loading,pathname])
  return <><div className={`loader ${loading?'':'loader--done'}`} aria-hidden="true"><div className="loader__brand">FERTECH®</div><div className="loader__count">{String(progress).padStart(3,'0')}</div><div className="loader__line"><i style={{transform:`scaleX(${progress/100})`}}/></div></div><div className="grain" aria-hidden="true"/><div ref={cursor} className="cursor" aria-hidden="true"><span ref={cursorLabel}>OPEN</span></div><div className={loading?'experience experience--loading':'experience'}>{children}</div></>
}
