import { collection, doc, getDoc, getDocs, orderBy, query } from 'firebase/firestore'
import { firestore } from './firebase'

export type Profile={name:string;role:string;intro:string;contactUrl:string;logoUrl:string;photoUrl:string;socialLinks:{name:string;href:string;icon:string}[];technologies:string[];aboutParagraphs:string[];highlights:{icon:string;title:string;description:string}[]}
export type HomeContent={heroEyebrow:string;heroHeadline:string;heroDescription:string;projectsButtonLabel:string;resumeButtonLabel:string;contactButtonLabel:string;stackTitle:string;stackGroups:{title:string;items:string[]}[];aboutTitle:string;highlightsTitle:string;capabilitiesTitle:string;projectsEyebrow:string;projectsTitle:string;projectsLinkLabel:string;projectsTotalLabel:string;blogEyebrow:string;blogTitle:string;contactTitle:string;contactDescription:string}
export type SiteContent={navigation:Record<string,string>;common:Record<string,string>;blog:Record<string,string>;projects:Record<string,string>;resume:Record<string,string>;architecture:Record<string,unknown>}
export type ProjectDetails={headline:string;overview:string;role:string;period:string;stack:string[];highlights:string[];responsibilities:string[];modules:{title:string;description:string;technologies:string[]}[];flows:{title:string;steps:string[]}[];metrics:string[];learnings:string[]}
export type Project={id:string;groupId:string;groupTitle:string;title:string;description:string;logo:string;tags:string[];projectUrl?:string;siteUrl?:string;architecture?:Record<string,unknown>;details?:ProjectDetails;sortOrder:number}
export type Article={slug:string;title:string;category:string;description:string;date:string;readTime:string;content:string;kind:string;sortOrder:number}

function required<T>(value:T|null|undefined,label:string):T{if(value===null||value===undefined)throw new Error(`Conteúdo obrigatório ausente no Firebase: ${label}`);return value}
async function one(name:string,id='main'){const snapshot=await getDoc(doc(firestore,name,id));if(!snapshot.exists())throw new Error(`Documento obrigatório ausente no Firebase: ${name}/${id}`);return snapshot.data()}
async function many(name:string){const snapshot=await getDocs(query(collection(firestore,name),orderBy('sort_order')));return snapshot.docs.map(item=>item.data())}

export async function getProfile():Promise<Profile>{const x:any=await one('profile');return{name:required(x.name,'profile.name'),role:required(x.role,'profile.role'),intro:required(x.intro,'profile.intro'),contactUrl:required(x.contact_url,'profile.contact_url'),logoUrl:required(x.logo_url,'profile.logo_url'),photoUrl:required(x.photo_url,'profile.photo_url'),socialLinks:required(x.social_links,'profile.social_links'),technologies:required(x.technologies,'profile.technologies'),aboutParagraphs:required(x.about_paragraphs,'profile.about_paragraphs'),highlights:required(x.highlights,'profile.highlights')}}
export async function getHomeContent():Promise<HomeContent>{const x:any=await one('home_content');return{heroEyebrow:required(x.hero_eyebrow,'home.hero_eyebrow'),heroHeadline:required(x.hero_headline,'home.hero_headline'),heroDescription:required(x.hero_description,'home.hero_description'),projectsButtonLabel:required(x.projects_button_label,'home.projects_button_label'),resumeButtonLabel:required(x.resume_button_label,'home.resume_button_label'),contactButtonLabel:required(x.contact_button_label,'home.contact_button_label'),stackTitle:required(x.stack_title,'home.stack_title'),stackGroups:required(x.stack_groups,'home.stack_groups'),aboutTitle:required(x.classic_about_title,'home.classic_about_title'),highlightsTitle:required(x.classic_highlights_title,'home.classic_highlights_title'),capabilitiesTitle:required(x.classic_capabilities_title,'home.classic_capabilities_title'),projectsEyebrow:required(x.projects_eyebrow,'home.projects_eyebrow'),projectsTitle:required(x.projects_title,'home.projects_title'),projectsLinkLabel:required(x.projects_link_label,'home.projects_link_label'),projectsTotalLabel:required(x.projects_total_label,'home.projects_total_label'),blogEyebrow:required(x.blog_eyebrow,'home.blog_eyebrow'),blogTitle:required(x.blog_title,'home.blog_title'),contactTitle:required(x.contact_title,'home.contact_title'),contactDescription:required(x.contact_description,'home.contact_description')}}
export async function getSiteContent():Promise<SiteContent>{const x:any=await one('site_content');return required(x.content,'site_content.content') as SiteContent}
export async function getProjects():Promise<Project[]>{const[g,p]:any=await Promise.all([many('project_groups'),many('projects')]);const names=new Map(g.map((x:any)=>[x.id,x.title]));return p.map((x:any)=>({id:x.id,groupId:x.group_id,groupTitle:required(names.get(x.group_id),`project_group/${x.group_id}`) as string,title:required(x.title,`projects/${x.id}/title`),description:required(x.description,`projects/${x.id}/description`),logo:required(x.logo,`projects/${x.id}/logo`),tags:required(x.tags,`projects/${x.id}/tags`),projectUrl:x.project_url??undefined,siteUrl:x.site_url??x.url??undefined,architecture:x.architecture??undefined,details:x.details??undefined,sortOrder:required(x.sort_order,`projects/${x.id}/sort_order`)}))}
export async function getArticles():Promise<Article[]>{const data:any=await many('articles');return data.map((x:any)=>({slug:x.slug,title:x.title,category:x.category,description:x.description,date:x.date,readTime:x.read_time,content:x.content,kind:x.kind,sortOrder:x.sort_order}))}
export async function getResume(){const[e,r,ed,t,settings]:any=await Promise.all([many('resume_experiences'),many('resume_roles'),many('resume_education'),many('resume_technologies'),one('resume_settings')]);return{experiences:e.map((x:any)=>({...x,roles:r.filter((role:any)=>role.experience_id===x.id)})),education:ed,technologies:t.map((x:any)=>x.name),aboutParagraphs:required(settings.about_paragraphs,'resume_settings.about_paragraphs'),languages:required(settings.languages,'resume_settings.languages'),sections:required(settings.sections,'resume_settings.sections'),location:required(settings.location,'resume_settings.location'),downloadLabel:required(settings.download_label,'resume_settings.download_label'),projectTechnologiesLabel:required(settings.project_technologies_label,'resume_settings.project_technologies_label')}}
