export type ArchitectureLayer={name:string;role:string}
export type ProjectInsight={overview:string;architecture:readonly ArchitectureLayer[];flow:readonly string[];highlights:readonly string[]}

const layer=(name:string,role:string):ArchitectureLayer=>({name,role})

const insights:Record<string,ProjectInsight>={
  fertec:{overview:'Portfólio editorial construído como aplicação estática internacionalizada, com preferências persistentes e uma camada própria de movimento e interação.',architecture:[layer('App Router','Rotas estáticas, metadados, sitemap e páginas dinâmicas de projeto.'),layer('Sistema visual','Tokens globais, componentes editoriais e temas claro/escuro persistentes.'),layer('Experiência','Animações por rota, revelação por scroll, cursor contextual e navegação reposicionável.')],flow:['Conteúdo tipado alimenta páginas e metadados','Next.js pré-renderiza rotas e imagens sociais','Preferências do visitante coordenam idioma, tema e navegação'],highlights:['SSG para todo o portfólio','Internacionalização em três idiomas','Acessibilidade e redução de movimento']},
  atacte:{overview:'Cofre pessoal multiplataforma que separa clientes web, mobile e desktop de uma API responsável por identidade, criptografia e dados sensíveis.',architecture:[layer('Clientes','Vue 3 no navegador, Expo no mobile e Electron no desktop.'),layer('API segura','Express organiza autenticação, senhas, notas, TOTP, validação e rate limiting.'),layer('Persistência','Prisma e PostgreSQL isolam os dados; segredos locais usam armazenamento seguro.')],flow:['Usuário autentica com senha e segundo fator','Cliente negocia tokens e envia dados protegidos','API valida, cifra e persiste o conteúdo'],highlights:['AES-256 e TOTP','Clientes para três plataformas','Defesas com Helmet, validação e rate limit']},
  valk:{overview:'Sistema de componentes distribuído por uma CLI, com temas e primitivas reutilizáveis para acelerar interfaces React sem impor uma aparência fechada.',architecture:[layer('Componentes','Primitivas React tipadas e compostas.'),layer('Tema','Tokens e estilos Tailwind personalizáveis pelo produto consumidor.'),layer('Distribuição','CLI instala código e dependências diretamente no projeto.')],flow:['Desenvolvedor escolhe um componente','CLI copia a implementação e resolve dependências','Projeto passa a controlar código, tema e evolução'],highlights:['Código sob controle do consumidor','API tipada','Documentação integrada']},
  vendedor:{overview:'Ecossistema comercial com aplicações web e mobile, API modular, integrações corporativas e processamento em tempo real para a operação de vendedores.',architecture:[layer('Canais','Painel React e aplicativo Expo compartilham os fluxos de clientes, rotas e pedidos.'),layer('Backend','NestJS organiza domínios comerciais, autenticação, notificações e jobs.'),layer('Integrações','Firebase, bancos corporativos, SFTP e serviços Google conectam a operação externa.')],flow:['Vendedor registra visita, cliente ou pedido','API valida regras e sincroniza fontes corporativas','Eventos atualizam dashboards, notificações e aplicativo'],highlights:['Operação offline no mobile','Tempo real com Socket.IO','Múltiplos bancos e conectores']},
  smart:{overview:'Plataforma de fidelidade consolidada que conecta painel administrativo, campanhas, pontuação, resgates e rotinas de integração com vendas externas.',architecture:[layer('Painel','SPA React/CoreUI concentra dashboards e operação.'),layer('API','Express e Sequelize expõem regras de clientes, vendas, pontos e prêmios.'),layer('Processamento','Bee-Queue, cron e jobs importam vendas, expiram pontos e disparam campanhas.')],flow:['Vendas chegam por upload, integração ou job','Serviços calculam elegibilidade e pontuação','Cliente consulta saldo e realiza resgates'],highlights:['MySQL e MongoDB no mesmo domínio','Filas para trabalho pesado','Integrações por SFTP, e-mail e SMS']},
  parceiro:{overview:'Serviço de automação operacional que transforma dados em comunicações e peças visuais distribuídas por WhatsApp.',architecture:[layer('API','NestJS expõe comandos e coordena os fluxos.'),layer('Mídia','Canvas e Jimp montam imagens personalizadas.'),layer('Persistência','Prisma registra execução e contexto operacional.')],flow:['Operação solicita uma comunicação','Serviço compõe texto e mídia','Entrega é registrada e enviada ao canal'],highlights:['Geração dinâmica de imagens','Automação orientada a scripts','Cliente HTTP isolado']},
  pintor:{overview:'Aplicativo híbrido do Clube Pro Pintor com uma única base Angular/Ionic distribuída para Android e iOS.',architecture:[layer('Interface','Páginas Ionic organizam produtos, cursos, pontos, perfil e resgates.'),layer('Camada nativa','Capacitor conecta push, analytics, haptics e recursos dos dispositivos.'),layer('Estado e rede','RxJS coordena navegação, sessões e chamadas aos serviços da plataforma.')],flow:['Usuário autentica no aplicativo','Telas consultam catálogo, cursos e fidelidade','Capacitor entrega notificações e telemetria'],highlights:['Build Android e iOS','Firebase Analytics e FCM','Navegação mobile modular']},
  dashboard:{overview:'Laboratório fullstack para construir dashboards configuráveis, combinando editor visual, autenticação e processamento de mídia.',architecture:[layer('Editor web','React, React RND e React Query formam o canvas interativo.'),layer('Domínio','NestJS separa autenticação e dashboards em módulos.'),layer('Persistência','Prisma grava usuários, layouts e configurações; Sharp trata imagens.')],flow:['Usuário monta widgets no canvas','Frontend salva posições e configuração','API valida e persiste a composição'],highlights:['Drag, resize e composição visual','JWT com Argon2','Pipeline Docker e Nginx']},
  gabriel:{overview:'Plataforma web para operação e conteúdo de arquitetura, combinando uma aplicação Next.js rica com API organizada em casos de uso.',architecture:[layer('Aplicação','Next.js renderiza áreas públicas e administrativas, galerias e relatórios.'),layer('Casos de uso','API Express separa controllers, entities, services e use cases.'),layer('Dados e jobs','Prisma persiste o domínio; tarefas agendadas e e-mail automatizam rotinas.')],flow:['Interface executa uma operação de conteúdo','Caso de uso aplica regras e acessa repositórios','Resultado atualiza páginas, relatórios ou notificações'],highlights:['Separação por casos de uso','Geração e visualização de PDF','Jobs e logs rotativos']},
  recomenda:{overview:'Sistema de recomendação e serviços para pintores distribuído em aplicativo Ionic, portal React, API NestJS e aplicação dedicada de push.',architecture:[layer('Aplicações','App Ionic e portal React atendem públicos e operação.'),layer('Backend','NestJS e Prisma organizam pintores, serviços, localização e identidade.'),layer('Comunicação','Firebase, SendGrid e o serviço push distribuem mensagens transacionais.')],flow:['Usuário informa perfil, localização ou necessidade','API relaciona categorias, pintores e serviços','Aplicações recebem recomendações e notificações'],highlights:['Quatro aplicações no repositório','Storage em S3','Autenticação social e push']},
  leoplus:{overview:'Programa de fidelidade multiparceiro com campanhas, catálogo de recompensas e integrações externas organizadas por domínio.',architecture:[layer('Portal','React reúne jornada do participante e operação.'),layer('Features','Estado e consultas são separados por recursos de negócio.'),layer('Integrações','Serviços REST conectam campanhas, parceiros e resgates.')],flow:['Participante entra em uma campanha','Eventos acumulam saldo e elegibilidade','Catálogo processa o resgate com parceiros'],highlights:['Estado sincronizado com React Query','Design system Material UI','Integrações desacopladas']},
  mimelie:{overview:'Monorepo de comércio próprio para uma marca de maquiagem, reunindo vitrine, painel, API, domínio compartilhado e processamento assíncrono.',architecture:[layer('Experiência comercial','Next.js entrega catálogo, conteúdo, sacola, checkout, SEO e PWA.'),layer('Núcleo transacional','NestJS, contratos Zod e domínio puro controlam estoque, preço e pedidos.'),layer('Processamento assíncrono','BullMQ, Redis, outbox e conectores isolam pagamentos, frete e marketplaces.')],flow:['Cliente monta a sacola e inicia o checkout','API reserva estoque e registra pedido/outbox','Worker processa provedores com idempotência e retentativas'],highlights:['ABAC dinâmico e sessões opacas','Prisma com catálogo regulatório e auditoria','Deploy dividido entre Cloudflare e Railway']},
  miraj:{overview:'MMORPG multicomponente com portal, launcher, cliente nativo, serviços de jogo e distribuição segura de releases sobre contratos explícitos.',architecture:[layer('Plano de produto','Portal Next.js, launcher e cliente C++ apresentam conta, atualização e mundo.'),layer('Plano de serviços','API .NET, Login, Main/Coordinator e Lobby governam identidade e sessões.'),layer('Distribuição e dados','R2 entrega releases imutáveis; PostgreSQL e Redis separam estado persistente e efêmero.')],flow:['Conta e personagem são geridos pela API','Launcher baixa manifesto e arquivos pelo Worker','Cliente recebe ticket do Login e entra no Lobby via Coordinator'],highlights:['Clean Architecture na API','C++20 com CMake e Wicked Engine','Releases atômicas por Git SHA']},
  miriam:{overview:'Portfólio artístico multilíngue que organiza maquiagem, fotografia, currículo e conteúdo social em uma experiência Vue responsiva.',architecture:[layer('Apresentação','Views e layouts Vue separam home, biografia, currículo e galerias.'),layer('Conteúdo','Componentes por domínio e seis catálogos de tradução alimentam a interface.'),layer('Entrega','Vite, páginas SEO geradas e funções Vercel publicam o site e estatísticas sociais.')],flow:['Rota escolhe uma área do portfólio','Locale resolve conteúdo e componentes da categoria','Galerias e currículo são renderizados ou exportados em PDF'],highlights:['Seis idiomas','PDF gerado no navegador','SEO estático por rota']},
  familia:{overview:'Produto familiar experimental com uma base Flutter para web/Android e backend orientado a domínios, tempo real, localização e notificações.',architecture:[layer('Aplicativo','Flutter organiza core compartilhado e features de memória, chat, listas e localização.'),layer('Backend modular','NestJS divide cada domínio em application, domain, infrastructure e interfaces.'),layer('Tempo real e tarefas','Socket.IO atualiza conversas/localização; Redis e BullMQ executam notificações e jobs.')],flow:['Aplicativo autentica e carrega permissões familiares','Recursos usam REST para estado e Socket.IO para eventos','Filas enviam notificações e processam mídia/localização'],highlights:['Uma UI para web e Android','Permissões por papel e área','CI/CD privado com Gitea Actions']},
  clienterei:{overview:'Plataforma omnichannel de relacionamento, pedidos e benefícios, com API em Clean Architecture, painel web e aplicativo Expo.',architecture:[layer('Domínio','Entidades, value objects e contratos de repositório preservam regras sem dependência externa.'),layer('Aplicação','Use cases cobrem carrinho, produtos, promoções, recompensas, solicitações e usuários.'),layer('Infraestrutura e canais','Adapters conectam PostgreSQL, MSSQL, MySQL, Redis, S3 e mensageria aos clientes web/mobile.')],flow:['Canal envia intenção de compra ou relacionamento','Use case valida domínio e consulta adapters','Jobs e integrações sincronizam ERP, notificações e relatórios'],highlights:['Clean Architecture real','Três bancos relacionais integrados','Testes por camada e feature toggles']},
  imperio:{overview:'Plataforma de delivery de bebidas com aplicativo, loja web, painel, API em tempo real e infraestrutura automatizada na GCP.',architecture:[layer('Canais','Expo atende consumidores; Vike/React atende loja, entregadores e administração.'),layer('Backend modular','NestJS separa pedidos, pagamentos, parceiros, produtos, entregadores e permissões.'),layer('Operação','Redis/BullMQ, Socket.IO, Firebase, Mercado Pago e observabilidade sustentam eventos e jobs.')],flow:['Cliente monta carrinho e confirma endereço/pagamento','API cria pedido e distribui eventos para loja e entregador','Socket.IO e push acompanham cada mudança de status'],highlights:['App integrity e SSL pinning','Métricas e logs estruturados','Terraform para Cloud Run e Cloud SQL']},
  morelli:{overview:'Plataforma de fidelidade e sell-out com portal do participante, painel operacional, antifraude e processamento de comprovantes.',architecture:[layer('Portal e painel','React/Redux separa jornadas da loja e módulos administrativos.'),layer('API','Express, controllers e classes de processo aplicam pontuação, estoque e resgates.'),layer('Dados e rotinas','Sequelize/MySQL, migrations, seeders e cron mantêm o estado operacional.')],flow:['Participante envia venda ou código','Operação valida produto, parceiro e critérios antifraude','Pontos liberados alimentam catálogo e resgate'],highlights:['Leitura de QR/barcode','Liberações e alterações em massa','Dashboards de sell-out']},
  rehau:{overview:'Plataforma de fidelidade para marceneiros e vendedores com submissão de vendas, OCR assíncrono, pontos, roleta e resgates.',architecture:[layer('Domínios CQRS','Commands, queries, eventos e value objects separam escrita e leitura por contexto.'),layer('Processamento','BullMQ coordena OCR, exportações e rotinas; Textract/Tesseract interpretam comprovantes.'),layer('Experiência e operação','React atende participante e administração com APIs e componentes dedicados.')],flow:['Participante envia comprovante de venda','Fila processa OCR e aplica validações de domínio','Aprovação gera pontos, números ou giros e habilita resgates'],highlights:['Arquitetura hexagonal por módulo','OCR com fallback entre provedores','Testes unitários, integração e Playwright']},
  'sw-platform':{overview:'Plataforma web completa do Clube Pro Pintor, abrangendo fidelidade, treinamento, conteúdo, antifraude, relatórios e administração.',architecture:[layer('Experiência','SPA React separa portal do pintor, painel administrativo e relatórios.'),layer('Serviços','Express e Sequelize organizam controllers, modelos, jobs e integrações.'),layer('Mídia e documentos','FFmpeg, Puppeteer e PDFKit tratam vídeos, certificados, relatórios e materiais.')],flow:['Pintor registra atividade, venda ou participação','API valida, pontua e atualiza benefícios','Painel acompanha antifraude, campanhas, conteúdo e resgates'],highlights:['Grande superfície operacional','Geração de documentos e vídeo','Swagger e testes de controllers']},
  'vendedor-ia':{overview:'Backend de IA para assistência comercial, combinando agente com ferramentas, conhecimento vetorial, dados operacionais e tarefas programadas.',architecture:[layer('Orquestração do agente','LangGraph seleciona prompts e ferramentas conforme intenção, contexto e permissões.'),layer('Casos de uso','Camadas de chats, ações, clientes, vendedores, agenda e conhecimento isolam regras.'),layer('Dados e execução','PostgreSQL/pgvector persistem contexto; Redis mantém checkpoints e workers executam tarefas.')],flow:['Usuário envia pergunta ou comando comercial','Agente planeja e chama ferramenta SQL, relatório, alerta ou visita','Resposta e efeitos passam por validação, auditoria e persistência'],highlights:['RAG com pgvector','Ferramentas especializadas por domínio','Checkpoints distribuídos e scheduler']},
}

export function getProjectInsight(id:string):ProjectInsight{
  return insights[id]??{overview:'Sistema organizado em aplicações, serviços e integrações especializadas.',architecture:[layer('Aplicações','Interfaces responsáveis pela experiência e operação.'),layer('Serviços','Regras de negócio e integrações coordenadas no backend.'),layer('Dados','Persistência e infraestrutura mantêm o estado do produto.')],flow:['A interface recebe a intenção do usuário','Serviços aplicam regras e acessam integrações','O estado atualizado retorna aos canais'],highlights:['Separação de responsabilidades','Componentes reutilizáveis','Integrações desacopladas']}
}
