import projectTrees from './project-trees.json'

export type TreeNode={name:string;type:'folder'|'file';children?:TreeNode[]}
export type Project={id:string;title:string;group:'personal'|'professional';url?:string;tags:readonly string[];technologies:readonly string[];services:readonly string[];repository:string;treeSource?:'reconstructed';tree:TreeNode[]}

const folder=(name:string,children:TreeNode[]=[]):TreeNode=>({name,type:'folder',children})
const file=(name:string):TreeNode=>({name,type:'file'})

const projectCatalog:Project[]=[
  {id:'fertec',title:'Fertec',group:'personal',url:'https://github.com/ferforastieri/fertech',repository:'pessoal/fertech',tags:['Next.js','TypeScript','Tailwind CSS'],technologies:['Next.js 16','React 19','TypeScript','Tailwind CSS 4','next-intl','Web Animations API','jsPDF','Manrope','Instrument Serif'],services:['Portfólio web','Sistema de animação','Internacionalização','Temas persistentes','PWA e SEO'],tree:[folder('app',[folder('(portfolio)',[folder('projetos',[folder('[slug]')]),folder('sobre'),folder('curriculo'),file('page.tsx')]),folder('components',[folder('ui'),folder('portfolio'),folder('projects'),folder('about'),folder('resume')]),folder('hooks'),file('globals.css')]),folder('i18n',[file('request.ts')]),folder('messages',[file('project-data.ts'),file('project-insights.ts'),file('pt-BR.json'),file('en.json'),file('es.json')]),folder('public',[folder('assets'),file('sw.js')]),file('next.config.ts')]},
  {id:'atacte',title:'Atacte',group:'personal',url:'https://github.com/ferforastieri/atacte',repository:'pessoal/atacte',tags:['Vue 3','Expo','Express'],technologies:['Vue 3','Pinia','Vue Router','React Native','Expo','Electron','Express','Prisma','PostgreSQL','JWT','TOTP','AES-256','Tailwind CSS'],services:['API segura','Cliente web','Aplicativo mobile','Aplicativo desktop','Proxy Nginx'],tree:[folder('backend',[folder('src',[folder('controllers',[folder('auth'),folder('passwords'),folder('secureNotes'),folder('totp')]),folder('repositories'),folder('services'),folder('middleware'),folder('infrastructure')])]),folder('desktop'),folder('mobile',[folder('assets'),folder('src')]),folder('web',[folder('public'),folder('src',[folder('components'),folder('stores'),folder('views'),folder('api')])]),folder('nginx'),folder('scripts')]},
  {id:'valk',title:'Valk UI',group:'personal',url:'https://valkui.vercel.app',repository:'github/ferforastieri/valk-ui',treeSource:'reconstructed',tags:['React','TypeScript','CLI'],technologies:['React','TypeScript','Tailwind CSS','Node.js CLI'],services:['Biblioteca de componentes','CLI de instalação','Documentação','Sistema de temas'],tree:[folder('src',[folder('components'),folder('cli'),folder('lib'),folder('styles')]),folder('docs'),folder('templates'),file('package.json')]},
  {id:'vendedor',title:'Vendedor Gold',group:'professional',url:'https://vendedorgold.com.br',repository:'smart/vendedor-gold',tags:['React Native','React','NestJS'],technologies:['React','React Native','Expo','TypeScript','NestJS','TypeORM','PostgreSQL','MongoDB','Firebase','Socket.IO','React Query','Zustand','Recharts'],services:['API NestJS','Firebase Functions','Painel web','Aplicativo mobile','Notificações e tempo real'],tree:[folder('backend',[folder('src',[folder('auth'),folder('business-unit'),folder('client'),folder('goldia'),folder('notification'),folder('order'),folder('popup')])]),folder('backend-firebase',[folder('functions')]),folder('mobile',[folder('src')]),folder('web',[folder('public'),folder('src',[folder('api'),folder('components'),folder('assets')])])]},
  {id:'smart',title:'Smart',group:'professional',repository:'smart/smart',tags:['Express','React','MySQL'],technologies:['Node.js','Express 4','React 16','Sequelize','MySQL','MongoDB','Mongoose','Bee-Queue','JWT','Reactstrap','CoreUI','Material UI','Chart.js','Draft.js','Node Cron','Nodemailer','SFTP'],services:['API de fidelidade','Painel administrativo','Campanhas de e-mail e SMS','Filas e rotinas agendadas','Pontuação e resgates','Cartões-presente','Relatórios e dashboards'],tree:[folder('api',[folder('scripts',[file('01_update_idLojaOrigem.js')]),folder('src',[folder('app',[folder('controllers',[file('AuthenticationController.js'),file('CampaignController.js'),file('CustomerControlller.js'),file('DashboardController.js'),file('GiftController.js'),file('RescueController.js'),file('SaleController.js')]),folder('middlewares'),folder('models',[file('Campanha.js'),file('Cliente.js'),file('Fidelidades.js'),file('Pontuacao.js'),file('Premio.js'),file('Resgate.js'),file('Venda.js')]),folder('schemas')]),folder('config',[file('EmailMarketingAPI.js'),file('Mongoose.js'),file('Sequelize.js'),file('SMSMarketingAPI.js')]),folder('database'),folder('jobs',[file('ExpireScore.job.js'),file('NewVendasRadical.job.js'),file('NewVendasSodimac.job.js')]),folder('lib'),folder('routes'),folder('services',[file('NovaVenda.js'),file('NovoEmailMarketing.js'),file('NovoSMSMarketing.js'),file('PontuarCliente.js')]),folder('utils')]),file('package.json')]),folder('web',[folder('public'),folder('src',[folder('components',[folder('Campanhas'),folder('Dashboard'),folder('GridClientes'),folder('GridProdutos'),folder('GridResgates'),folder('Widgets')]),folder('containers'),folder('context'),folder('routes'),folder('scss'),folder('services'),folder('views',[folder('Pages'),folder('Theme')])]),file('package.json')]),file('bitbucket-pipelines.yml'),file('pm2.json')]},
  {id:'parceiro',title:'Parceiro Gold',group:'professional',url:'https://parceirogold.com.br',repository:'smart/wpp-parceirogold',tags:['NestJS','Prisma','WhatsApp'],technologies:['NestJS','TypeScript','Prisma','Axios','Canvas','Jimp','RxJS'],services:['Automação WhatsApp','Geração de mídia','Persistência Prisma','Rotinas operacionais'],tree:[folder('src',[folder('config'),folder('helpers'),folder('scripts')]),folder('prisma'),folder('test'),folder('img',[folder('generated')]),folder('fonts')]},
  {id:'pintor',title:'Clube Pro Pintor',group:'professional',url:'https://clubepropintor.com.br',repository:'smart/sw-app',tags:['Ionic','Angular','Capacitor'],technologies:['Ionic','Angular','TypeScript','Capacitor','RxJS','Firebase Analytics','Firebase Cloud Messaging','Swiper'],services:['Aplicativo Ionic','Build Android','Build iOS','Push notifications','Analytics'],tree:[folder('src',[folder('app'),folder('assets'),folder('environments'),folder('theme')]),folder('android',[folder('app'),folder('gradle')]),folder('ios',[folder('App')]),folder('resources'),folder('e2e')]},
  {id:'dashboard',title:'Dashlab',group:'personal',url:'https://github.com/ferforastieri/dashlab',repository:'pessoal/dashlab',tags:['NestJS','React','Prisma'],technologies:['NestJS','React','TypeScript','Prisma','React Query','Vite','Tailwind CSS','Argon2','JWT','Sharp'],services:['API NestJS','Editor de dashboards','Autenticação','Processamento de imagens'],tree:[folder('backend',[folder('prisma'),folder('src',[folder('infrastructure',[folder('database')]),folder('modules',[folder('auth'),folder('dashboard')])])]),folder('web',[folder('public'),folder('scripts'),folder('src',[folder('api'),folder('components'),folder('pages')])]),folder('nginx'),folder('.gitea',[folder('workflows')])]},
  {id:'gabriel',title:'GabrielPro',group:'professional',url:'https://gabrielpro.com.br',repository:'smart/gabrielpro',tags:['Next.js','Express','Prisma'],technologies:['Next.js','React','TypeScript','Express','Prisma','Styled Components','Bootstrap','JWT','Winston','Node Schedule'],services:['API Express','Aplicação Next.js','Jobs agendados','Relatórios e dashboards'],tree:[folder('api',[folder('prisma'),folder('src',[folder('controllers'),folder('entities'),folder('infra'),folder('jobs'),folder('services'),folder('usecases')])]),folder('app',[folder('public'),folder('src',[folder('components'),folder('pages'),folder('services'),folder('views')])]),folder('nginx')]},
  {id:'recomenda',title:'SW Recomenda',group:'professional',repository:'smart/sw-recomenda',tags:['Ionic','React','NestJS'],technologies:['Ionic','Angular','React','Material UI','NestJS','Prisma','AWS S3','Firebase','SendGrid','Redux','Capacitor'],services:['Aplicativo Ionic','API NestJS','Portal React','Aplicação de push','Storage S3'],tree:[folder('app',[folder('android'),folder('ios'),folder('src')]),folder('backend',[folder('prisma'),folder('src',[folder('auth'),folder('localizacao'),folder('mail'),folder('notificacoesPush'),folder('pintores'),folder('servicosCategorias')])]),folder('frontend',[folder('public'),folder('src',[folder('components'),folder('pages'),folder('services')])]),folder('push',[folder('src')])]},
  {id:'leoplus',title:'LeoPlus',group:'professional',url:'https://leoplus.com.br',repository:'private/leoplus',treeSource:'reconstructed',tags:['React','TypeScript','APIs'],technologies:['React','TypeScript','Material UI','Zustand','React Query','REST APIs'],services:['Portal de fidelidade','Campanhas','Resgates','Integrações com parceiros'],tree:[folder('frontend',[folder('src',[folder('components'),folder('features'),folder('services')])]),folder('api',[folder('src',[folder('modules'),folder('integrations')])]),folder('infrastructure')]},
  {id:'mimelie',title:'Mimelie',group:'personal',repository:'pessoal/Mimelie',tags:['Next.js','NestJS','BullMQ'],technologies:['Turborepo','pnpm workspaces','Next.js','React','NestJS','Prisma','PostgreSQL','Redis','BullMQ','Cloudflare Workers','Railway','Zod'],services:['Loja e PWA','Painel operacional','API REST','Worker assíncrono','Outbox e webhooks','Integrações de pagamento e frete'],tree:[folder('apps',[folder('web',[folder('app'),folder('components'),folder('lib')]),folder('api',[folder('src',[folder('auth'),folder('catalog'),folder('orders'),folder('webhooks')])]),folder('worker',[folder('src',[folder('connectors')])])]),folder('packages',[folder('config'),folder('contracts'),folder('database'),folder('domain'),folder('ui')]),folder('scripts',[file('backup-postgres.sh')]),file('docker-compose.yml'),file('turbo.json')]},
  {id:'miraj',title:'Miraj of Icarus',group:'personal',repository:'pessoal/miraj-of-icarus',tags:['.NET 10','C++20','Next.js'],technologies:['.NET 10','ASP.NET Core','Entity Framework Core','C++20','CMake','Wicked Engine','Next.js 16','React 19','PostgreSQL','Redis','Cloudflare Workers','R2','Docker Compose','Caddy'],services:['Portal e PWA','API de contas e personagens','Launcher Windows','Cliente nativo','Login Server','Coordinator e Lobby','Distribuição de releases'],tree:[folder('apps',[folder('game',[folder('windows',[folder('common'),folder('launcher')]),folder('mobile')]),folder('portal',[folder('web',[folder('src',[folder('app'),folder('components'),folder('i18n')])])])]),folder('backend',[folder('api',[folder('src',[folder('Api'),folder('Application'),folder('Domain'),folder('Infrastructure')])]),folder('download-worker'),folder('game-server'),folder('infra')]),folder('reverse-engineering',[folder('api'),folder('database'),folder('game'),folder('tooling')]),file('global.json')]},
  {id:'miriam',title:'Mundo de Miriam',group:'personal',repository:'pessoal/mundo-de-miriam',tags:['Vue 3','i18n','Vite'],technologies:['Vue 3','Vue Router','Vue I18n','TanStack Vue Query','Vite','HTML2Canvas','HTML2PDF','Vercel'],services:['Portfólio artístico','Galerias por categoria','Currículo em PDF','Internacionalização em seis idiomas','SEO estático','Estatísticas do Instagram'],tree:[folder('src',[folder('api',[folder('dashboard'),folder('storage'),folder('translation')]),folder('components',[folder('about'),folder('common'),folder('curriculum'),folder('home'),folder('portfolio')]),folder('layouts'),folder('locales'),folder('router'),folder('views')]),folder('api',[file('instagram-stats.js')]),folder('scripts',[file('generate-seo-pages.mjs')]),folder('public',[folder('assets')]),file('vercel.json')]},
  {id:'familia',title:'Nossa Família',group:'personal',repository:'pessoal/my-family',tags:['Flutter','NestJS','Socket.IO'],technologies:['Flutter','Dart','NestJS','MongoDB','Mongoose','Redis','BullMQ','Socket.IO','Firebase Cloud Messaging','Docker Compose','Nginx','Gitea Actions'],services:['Aplicativo Flutter web e Android','API modular','Chat em tempo real','Memórias e mídia','Listas compartilhadas','Localização familiar','Notificações e filas'],tree:[folder('app',[folder('lib',[folder('core',[folder('api'),folder('auth'),folder('location'),folder('notifications'),folder('socket')]),folder('features',[folder('admin'),folder('chat'),folder('content'),folder('games'),folder('lists'),folder('location'),folder('profile')])]),folder('android'),folder('web')]),folder('backend',[folder('src',[folder('auth'),folder('cartas'),folder('chat'),folder('fotos'),folder('games'),folder('lists'),folder('location'),folder('notifications'),folder('shared')])]),folder('nginx'),file('docker-compose.yml')]},
  {id:'clienterei',title:'ClienteRei',group:'professional',repository:'smart/clienterei',tags:['Clean Architecture','React','Expo'],technologies:['TypeScript','Express','Fastify','Prisma','PostgreSQL','Redis','MSSQL','MySQL','React','Vite','React Native','Expo','React Query','Zustand','AWS S3','Twilio'],services:['API multi-integração','Portal de loja e painel','Aplicativo mobile','Carrinho e pedidos','Clube de benefícios','Promoções e cupons','Sincronizações e jobs'],tree:[folder('api',[folder('src',[folder('application',[folder('services'),folder('usecases')]),folder('domain',[folder('entities'),folder('repositories'),folder('value-objects')]),folder('infrastructure',[folder('database'),folder('files'),folder('cron')]),folder('presentation',[folder('controllers')])])]),folder('web',[folder('src',[folder('pages'),folder('service'),folder('stores'),folder('translate')])]),folder('mobile',[folder('src',[folder('components'),folder('hooks'),folder('service'),folder('translate')])]),file('bitbucket-pipelines.yml')]},
  {id:'imperio',title:'Império Delivery',group:'professional',repository:'smart/imperio-delivery',tags:['NestJS','Expo','Vike'],technologies:['Turborepo','NestJS 11','TypeORM','PostgreSQL','MongoDB','Redis','BullMQ','Socket.IO','Expo','React Native','React 19','Vike','Mercado Pago','Firebase','Terraform','GCP'],services:['Aplicativo de delivery','Loja web','Painel administrativo','API e worker','Pedidos em tempo real','Pagamentos','Push notifications','Infraestrutura como código'],tree:[folder('apps',[folder('api',[folder('src',[folder('common'),folder('infrastructure'),folder('modules'),folder('worker')])]),folder('mobile',[folder('src',[folder('navigation'),folder('screens'),folder('security'),folder('stores')])]),folder('web',[folder('src',[folder('components'),folder('pages'),folder('stores')])])]),folder('packages',[folder('shared')]),folder('infra',[folder('terraform')]),file('docker-compose.yml'),file('turbo.json')]},
  {id:'morelli',title:'Morelli',group:'professional',repository:'smart/morelli',tags:['React','Express','Sequelize'],technologies:['React','Redux','Redux Saga','React Query','Express','Sequelize','MySQL','JWT','Recharts','ZXing','Quagga','Docker Compose'],services:['Portal de fidelidade','Painel administrativo','Pontuação por vendas','Resgates e prêmios','Antifraude','Leitura de código de barras','Relatórios operacionais'],tree:[folder('api',[folder('src',[folder('app',[folder('controllers'),folder('middlewares'),folder('models')]),folder('classes'),folder('database',[folder('migrations'),folder('seeders')]),folder('jobs')])]),folder('app',[folder('src',[folder('components',[folder('Loja'),folder('Painel'),folder('shared')]),folder('config'),folder('hooks')])]),file('docker-compose.yml'),file('bitbucket-pipelines.yml')]},
  {id:'rehau',title:'Rehau Loyalty',group:'professional',repository:'smart/rehau',tags:['CQRS','NestJS','OCR'],technologies:['NestJS','CQRS','TypeORM','PostgreSQL','Redis','BullMQ','AWS S3','AWS Textract','Tesseract.js','React 19','Vite','React Query','Tailwind CSS','Playwright','Vitest'],services:['Portal do participante','Painel administrativo','Envio e validação de vendas','OCR assíncrono','Pontos e roleta','Prêmios e resgates','Exportações e push'],tree:[folder('api',[folder('src',[folder('modules',[folder('admin',[folder('application'),folder('domain'),folder('infrastructure'),folder('interfaces')]),folder('auth'),folder('participant'),folder('registration')]),folder('shared'),folder('migrations')])]),folder('web',[folder('src',[folder('api'),folder('components'),folder('pages')]),folder('e2e')]),file('docker-compose.yml')]},
  {id:'sw-platform',title:'Clube Pro Pintor · Plataforma',group:'professional',repository:'smart/sw',tags:['React','Express','Sequelize'],technologies:['React','Redux Saga','Express','Sequelize','MySQL','Firebase','AWS SDK','FFmpeg','Puppeteer','PDFKit','Swagger','Docker'],services:['Portal do pintor','Painel administrativo','API de fidelidade','Cursos e treinamentos','Pontuação e resgates','Antifraude','Mídia, relatórios e PDFs'],tree:[folder('sw_api',[folder('src',[folder('app',[folder('controllers'),folder('middlewares'),folder('models')]),folder('classes'),folder('database',[folder('migrations')]),folder('jobs'),folder('utils')])]),folder('sw_app',[folder('src',[folder('components',[folder('Loja'),folder('Painel'),folder('Relatorio')]),folder('pages'),folder('hooks')])]),file('bitbucket-pipelines.yml')]},
  {id:'vendedor-ia',title:'Vendedor Gold IA',group:'professional',repository:'smart/vendedor-gold-ia-backend',tags:['FastAPI','LangGraph','pgvector'],technologies:['Python','FastAPI','LangChain','LangGraph','OpenAI API','SQLAlchemy','PostgreSQL','pgvector','Redis','APScheduler','AWS S3','Docker'],services:['Assistente comercial com IA','Agente com ferramentas','Consultas e relatórios','Base de conhecimento vetorial','Alertas e agendamentos','Histórico de conversas','Workers assíncronos'],tree:[folder('app',[folder('adapters',[folder('agent',[folder('prompts'),folder('services'),folder('tools',[folder('alerts'),folder('entities'),folder('reports'),folder('sql'),folder('visits')])]),folder('llm'),folder('repositories')]),folder('api',[folder('middlewares'),folder('routers')]),folder('schemas'),folder('services'),folder('use_cases',[folder('actions'),folder('chats'),folder('knowledge_base'),folder('notifications'),folder('schedules'),folder('sellers')]),folder('workers')]),folder('alembic'),folder('tests'),file('docker-compose.yml'),file('requirements.txt')]},
]

const generatedTrees=projectTrees as unknown as Record<string,TreeNode[]>
export const projects:Project[]=projectCatalog
  .map(project=>({...project,url:project.id==='miraj'?'https://mirajoficarus.com/':project.url,tree:generatedTrees[project.id]??project.tree}))
  .sort((a,b)=>Number(b.id==='miraj')-Number(a.id==='miraj'))

export function getProject(id:string){return projects.find(project=>project.id===id)}
